import 'package:recordo/features/parks/park.dart';

/// Seed skeleton — Places-shaped HK parks (replace/enrich with Google later).
/// Coords approx; for UI dogfood without API key.
final List<Park> hkSeedParks = [
  Park(
    id: 'ts_causeway',
    name: 'Times Square Car Park',
    district: 'Causeway Bay',
    lat: 22.2783,
    lng: 114.1827,
    hourlyHkd: 32,
    dailyHkd: 250,
    nightHkd: 120,
    heightM: 2.1,
    ugcConfirms: 4,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 5)),
  ),
  Park(
    id: 'ifc_central',
    name: 'IFC Mall Car Park',
    district: 'Central',
    lat: 22.2855,
    lng: 114.158,
    hourlyHkd: 30,
    dailyHkd: null,
    nightHkd: null,
    heightM: 2.1,
    ugcConfirms: 2,
    priceUpdatedAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  Park(
    id: 'hc_tst',
    name: 'Harbour City Car Park',
    district: 'Tsim Sha Tsui',
    lat: 22.295,
    lng: 114.168,
    hourlyHkd: 28,
    dailyHkd: 220,
    heightM: 2.2,
    ugcConfirms: 6,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 12)),
  ),
  Park(
    id: 'festival_kln',
    name: 'Festival Walk Car Park',
    district: 'Kowloon Tong',
    lat: 22.337,
    lng: 114.174,
    hourlyHkd: 22,
    heightM: 2.1,
    ugcConfirms: 1,
    priceUpdatedAt: DateTime.now().subtract(const Duration(days: 3)),
  ),
  Park(
    id: 'ntp_shatin',
    name: 'New Town Plaza Car Park',
    district: 'Sha Tin',
    lat: 22.382,
    lng: 114.188,
    hourlyHkd: 15,
    dailyHkd: 90,
    heightM: 2.4,
    ugcConfirms: 3,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 30)),
  ),
  Park(
    id: 'apm_kt',
    name: 'apm Car Park',
    district: 'Kwun Tong',
    lat: 22.312,
    lng: 114.225,
    hourlyHkd: 18,
    heightM: 2.0,
    ugcConfirms: 0,
    priceUpdatedAt: null,
  ),
  Park(
    id: 'vpark_unknown',
    name: 'Lee Garden One Car Park',
    district: 'Causeway Bay',
    lat: 22.2789,
    lng: 114.1845,
    // no seed price → UGC empty state
  ),
  Park(
    id: 'elements_wkr',
    name: 'Elements Car Park',
    district: 'West Kowloon',
    lat: 22.3045,
    lng: 114.1615,
    hourlyHkd: 26,
    heightM: 2.2,
    ugcConfirms: 2,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 8)),
  ),
  Park(
    id: 'yoho_yl',
    name: 'YOHO Mall Car Park',
    district: 'Yuen Long',
    lat: 22.445,
    lng: 114.036,
    hourlyHkd: 12,
    heightM: 2.4,
    ugcConfirms: 5,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  Park(
    id: 'vp_cwb',
    name: 'Victoria Park Car Park',
    district: 'Causeway Bay',
    lat: 22.2825,
    lng: 114.189,
    hourlyHkd: 26,
    dailyHkd: 180,
    nightHkd: 90,
    heightM: 2.0,
    ugcConfirms: 8,
    priceUpdatedAt: DateTime.now().subtract(const Duration(hours: 1)),
  ),
];
